service: sample-slack-app

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs20.x
  timeout: 25
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  SlackBolt:
    handler: app.handler
    events:
      - httpApi:
          shouldStartNameWithService: true
          disableDefaultEndpoint: true
          path: slack/events
          method: post

plugins:
  - serverless-offline