service: my-slack

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  tags:
    service: my-slack
  runtime: nodejs20.x
  timeout: 25
  versionFunctions: false
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

  httpApi:
    shouldStartNameWithService: true
    disableDefaultEndpoint: true

functions:
  accept:
    handler: app.accept
    events:
      - httpApi:
          method: post
          path: /slack/events
    destinations:
      onSuccess: bolt

  bolt:
    handler: app.handler

plugins:
  - serverless-offline